name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: graphqlide-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '17.6.0'

      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.8'

      - run: make .rocks
      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag $TAG
      - run: sed -i "s/local VERSION = 'scm-1'/local VERSION = '"$TAG"-1'/g" graphqlide.lua
      - run: tarantoolctl rocks make graphqlide-$TAG-1.rockspec
      - run: tarantoolctl rocks pack graphqlide $TAG

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: |
            graphqlide-$TAG-1.rockspec
            graphqlide-$TAG-1.all.rock
