name: Run tests

on: [push]

jobs:
  all:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN }}
      ROCKS_USERNAME: ${{ secrets.ROCKS_USERNAME }}
      ROCKS_PASSWORD: ${{ secrets.ROCKS_PASSWORD }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install npm
        uses: actions/setup-node@v1
        with:
          node-version: '17.8.0'
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.8'
      - name: Install rocks
        shell: bash
        run: make .rocks
      - name: Run tests
        run: make test
